# Project information
site_name: Abstract Matter
#site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Nilay Doshi
site_description: >-
  Abstract matter is a coalition of thoughts and experience that takes a very different perspective on the world around us. 
  The topics of discussion include Data Science, Machine Learning, Artificial Intelligence and how these integrate into industry and philosophy.

# Repository
# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2015 - 2024 Nilay Doshi

# Configuration
theme:
  name: material
  logo: assets/images/Transparent Logo.png
  favicon: assets/images/Transparent Logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black  
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/nilaykd
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nilaykdoshi/
  homepage: https://abstractmatter.io/blog/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright:  |
  &copy; 2024 <a href="https://github.com/nilaykd" target="_blank" rel="noopener">Nilay Doshi</a> 

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social
  - tags:
      tags_file: tags.md

# Page tree
nav:
  - About: about.md
  - Blog:
    - blog/index.md
  - Tags: tags.md